#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "sales/tax"

cli = Sales::Tax::CLI.new

if ARGV[0].nil?
  puts "Missing Input information :)"
else
  begin
    products = cli.load(ARGV[0])
    cli.run(products)
  rescue Errno::ENOENT => e
    puts e.message.to_s
  end
end
